### ISSUE TITLE
Rethinking CacheSyncOperation in CacheRepository

### ISSUE THREAD

**Issue by vilanovi** [mobilejazz/harmony-reference#16]
I see a problem with the current CacheSyncOperation on GET methods. Mostly this is what the repository does:

1. Fetch cache data
2. If data is "valid", return data
3. If data is "not valid", fetch network data
4. If data is fetched successfully, return data
5. If data is not fetched (server down, for example), return an error

My main problem is on point 5, as even if we have a cached version of the data (which was not valid), we are reporting an error to the user missing the chance of delivering him "old cached data".

To fix this, we would need to deprecate the `DataSourceValidator` and merge it into the `CacheRepository`, as now is the repository who is responsible for validating data and decide which data to give back to the user (either cached data or network data).

Note we could apply this behavior on the already existing `CacheSyncOperation` or create a new operation type like `CacheSyncFallbackOperation`.

This is something I'd like to get implemented in a project I'm developing right now. Therefore, your fast feedback is appreciated.

**Comment by Atternatt** [comment]
Does this mean that it won't use Vastra anymore but it'll be "included" in the cacheRepo?

**Comment by franmontiel** [comment]
I agree that it is a very useful feature to have. I am okey with the proposed change.
I would add a new `CacheSyncFallbackOperation` because there can be some use cases were you don't wanna show outdated information.

@Atternatt in this case we should be using vastra ValidationService inside CacheRepository so Vastra will still be used.

**Comment by vilanovi** [comment]
exactly, the point is that we need to do the validation inside the `CacheRepository` rather than having a `DataSourceValidation`, as otherwise the `CacheRepository` would always have a `NotValid` error from the cache and could not return the non-valid but cached data.

**Comment by vilanovi** [comment]
Also, the `DefaultOperation` should be redirected then to.. 

1. `CacheSyncOperation`
2. `CacheSyncFallbackOperation`

What do you think it should do?

**Comment by joselufo** [comment]
Agree that can be a useful feature but I have a concern about creating a new Operation just for this new feature when it's basically if an error happens we are going to return the cache data. 

So why not instead of creating a new `CacheSyncFallbackOperation` operation, we just add a new property to the `CacheSyncOperation` called fallback and for example, instead to have a simple boolean we could have a function that returns a boolean. 

So we could add custom logic to each operation if needed. 

Default will be always true. 
`CacheSyncOperation(fallback = () -> { println("validate everything") return true } )`

**Comment by franmontiel** [comment]
What could be the purpose of the custom logic on the fallback function @joselufo?

**Comment by joselufo** [comment]
For example, the fallback function could have by parameter (value, error) and if the error is a 401, you just don't want to show information to the user for example. 

Or if the value, after you reviewed in the fallback function you just don't want to display it. 

--------

My point here is two things:
1. We need to think first if a new Operation / Query is needed or if we could just reuse one of the current ones but giving them more power, for example, adding properties. If not, we are going to end up with more and more classes to just do a small thing that it's related to another thing. 

2. If we want fallback functionality, I would say that we need to have something open to customization rather than something hardcode for example,  if an error happens return old data. If not we are going to end up with another problem in the future.

**Comment by franmontiel** [comment]
Completelly agree with Jose proposal for the modification of CacheSyncOperation

**Comment by franmontiel** [comment]
By the way taking Jose's sample into accoutn the fallback function should be like this to allow to pass the error into the function:
`CacheSyncOperation(fallback = (throwable: Throwable) -> { println("validate everything") return true } )`

Also note that this will require a refactor in Android apps at least because right now CacheSyncOperation is an object and with this change we must transform it into a class.



Should add in that

**Comment by joselufo** [comment]
Agree with do not allow by default.

**Comment by RubenVot** [comment]
The proposal of @joselufo looks brilliant. +1 for me and also to keep the current behavior by default.

**Comment by newboadki** [comment]
- I prefer the proposal to extend the existing CacheSyncOperation with a fallback parameter.

Question: I understand the reasoning behind removing DataSourceValidator and merging it into CacheRepository, but do we need to deprecate it? I think that class is still valid, since CacheRepository is a concrete implementation. @vilanovi

**Comment by vilanovi** [comment]
I love your idea @joselufo. Let's extend it as you described!

**Comment by vilanovi** [comment]
Already implemented in Swfit!

**Comment by franmontiel** [comment]
I've encountered the exact same problem with `MainSyncOperation`.
I need to obtain data from the network but if something fails and I have the data already cached(and valid) I want to obtain it.

So my proposal is to do the exact same change that is approved for the `CacheSyncOperation` to the `MainSyncOperation`.

Any concerns?

**Comment by franmontiel** [comment]
Implemented in Android too. 

Nothing was done on the `MainSyncOperation` that I mentioned in the previous comment as I want to think about it and open a new thread to discuss it.

Closing this
